name: Ramblings
description: Indo-Canadian, Colloquial, Unrated
meta_description: "Ramblings of a madman"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: 'http://colloquial.me'
google_analytics: 'UA-106624228-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://colloquial.me'
author:         'Bhargav R. Patel'
